name: check pnpm project
description: 'Install nodejs and pnpm environment and run most commons checks'

branding:
  icon: 'check-square'
  color: 'green'

inputs:
  pnpm-version:
    required: false
    description: pnpm major version
    default: '9'
  node-version:
    required: false
    description: nodejs version
    default: lts/iron

runs:
  using: 'composite'
  steps:
    - uses: emocional/action-pnpm-install@main
      with:
        node-version: ${{ inputs.node-version }}
        pnpm-version: ${{ inputs.pnpm-version }}

    - name: Commit lint
      uses: wagoid/commitlint-github-action@v5

    - name: Check
      shell: sh
      run: pnpm check

    - name: Build production
      shell: sh
      env:
        NODE_ENV: production
      run: pnpm build

    - name: Test
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        skip-step: install
        output: comment, report-markdown
        package-manager: pnpm
        test-script: pnpm test:cov

